/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dbg.proto */

#ifndef PROTOBUF_C_dbg_2eproto__INCLUDED
#define PROTOBUF_C_dbg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Dbg__SysInfo Dbg__SysInfo;
typedef struct _Dbg__Request Dbg__Request;
typedef struct _Dbg__Response Dbg__Response;


/* --- enums --- */

typedef enum _Dbg__Request__Type {
  /*
   * Note: Keep table in sync with dbgd.c!
   */
  DBG__REQUEST__TYPE__SYSINFO = 0,
  DBG__REQUEST__TYPE__REBOOT = 1,
  DBG__REQUEST__TYPE__MALLOC = 2,
  DBG__REQUEST__TYPE__FREE = 3,
  DBG__REQUEST__TYPE__MEM_READ = 4,
  DBG__REQUEST__TYPE__MEM_WRITE = 5,
  DBG__REQUEST__TYPE__DEBUG_PRINT = 6,
  DBG__REQUEST__TYPE__SHOW_DEBUG_SCREEN = 7,
  DBG__REQUEST__TYPE__SHOW_FRONT_SCREEN = 8,
  DBG__REQUEST__TYPE__COUNT = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DBG__REQUEST__TYPE)
} Dbg__Request__Type;
typedef enum _Dbg__Response__Type {
  DBG__RESPONSE__TYPE__OK = 0,
  DBG__RESPONSE__TYPE__ERROR_UNSUPPORTED = 1,
  DBG__RESPONSE__TYPE__ERROR_INCOMPLETE_REQUEST = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DBG__RESPONSE__TYPE)
} Dbg__Response__Type;

/* --- messages --- */

struct  _Dbg__SysInfo
{
  ProtobufCMessage base;
  int64_t tick_count;
};
#define DBG__SYS_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg__sys_info__descriptor) \
    , 0 }


struct  _Dbg__Request
{
  ProtobufCMessage base;
  /*
   */
  Dbg__Request__Type type;
  /*
   * DEBUG_PRINT
   */
  char *msg;
  /*
   * FREE, MEM_READ, MEM_WRITE
   */
  protobuf_c_boolean has_address;
  int32_t address;
  /*
   * MALLOC, MEM_READ, MEM_WRITE
   */
  protobuf_c_boolean has_size;
  int32_t size;
  /*
   * MEM_WRITE
   */
  protobuf_c_boolean has_value;
  int64_t value;
};
#define DBG__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg__request__descriptor) \
    , 0, NULL, 0,0, 0,0, 0,0 }


struct  _Dbg__Response
{
  ProtobufCMessage base;
  /*
   */
  Dbg__Response__Type type;
  /*
   */
  char *msg;
  /*
   * SYSINFO
   */
  Dbg__SysInfo *info;
  /*
   * MALLOC
   */
  protobuf_c_boolean has_address;
  int32_t address;
  /*
   * 
   */
  protobuf_c_boolean has_size;
  int32_t size;
  /*
   * MEM_READ
   */
  protobuf_c_boolean has_value;
  int64_t value;
};
#define DBG__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbg__response__descriptor) \
    , 0, NULL, NULL, 0,0, 0,0, 0,0 }


/* Dbg__SysInfo methods */
void   dbg__sys_info__init
                     (Dbg__SysInfo         *message);
size_t dbg__sys_info__get_packed_size
                     (const Dbg__SysInfo   *message);
size_t dbg__sys_info__pack
                     (const Dbg__SysInfo   *message,
                      uint8_t             *out);
size_t dbg__sys_info__pack_to_buffer
                     (const Dbg__SysInfo   *message,
                      ProtobufCBuffer     *buffer);
Dbg__SysInfo *
       dbg__sys_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg__sys_info__free_unpacked
                     (Dbg__SysInfo *message,
                      ProtobufCAllocator *allocator);
/* Dbg__Request methods */
void   dbg__request__init
                     (Dbg__Request         *message);
size_t dbg__request__get_packed_size
                     (const Dbg__Request   *message);
size_t dbg__request__pack
                     (const Dbg__Request   *message,
                      uint8_t             *out);
size_t dbg__request__pack_to_buffer
                     (const Dbg__Request   *message,
                      ProtobufCBuffer     *buffer);
Dbg__Request *
       dbg__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg__request__free_unpacked
                     (Dbg__Request *message,
                      ProtobufCAllocator *allocator);
/* Dbg__Response methods */
void   dbg__response__init
                     (Dbg__Response         *message);
size_t dbg__response__get_packed_size
                     (const Dbg__Response   *message);
size_t dbg__response__pack
                     (const Dbg__Response   *message,
                      uint8_t             *out);
size_t dbg__response__pack_to_buffer
                     (const Dbg__Response   *message,
                      ProtobufCBuffer     *buffer);
Dbg__Response *
       dbg__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbg__response__free_unpacked
                     (Dbg__Response *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Dbg__SysInfo_Closure)
                 (const Dbg__SysInfo *message,
                  void *closure_data);
typedef void (*Dbg__Request_Closure)
                 (const Dbg__Request *message,
                  void *closure_data);
typedef void (*Dbg__Response_Closure)
                 (const Dbg__Response *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dbg__sys_info__descriptor;
extern const ProtobufCMessageDescriptor dbg__request__descriptor;
extern const ProtobufCEnumDescriptor    dbg__request__type__descriptor;
extern const ProtobufCMessageDescriptor dbg__response__descriptor;
extern const ProtobufCEnumDescriptor    dbg__response__type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_dbg_2eproto__INCLUDED */
